### ISSUE TITLE
No tutorial 

### ISSUE THREAD

**Issue by Krabyz** [Radar4Albion/Gathering-Bot-Albion#1]
I download a python still cant open the program. Pls add tutorial how to use the bot thx

**Comment by Radar4Albion** [comment]
you can send me your discord and i can explain in screenshots

**Comment by Krabyz** [comment]
My disc is Krabs#4462 thx man

**Comment by Radar4Albion** [comment]
> Krabs#4462

added

**Comment by Krabyz** [comment]
thx
